### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [tinkertanker/pxt-rotary-encoder-ky040#4]
Hi @tinkertanker,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> 1. Use of mbed APIs that are in the compatibility layer, but no inclusion of mbed.h

```
/home/build/prjclone/pxtapp/ky040/ky040.cpp:3:9: error: 'vector' does not name a type
 typedef vector<Action> vA;
         ^~~~~~
/home/build/prjclone/pxtapp/ky040/ky040.cpp:31:25: error: 'InterruptIn' does not name a type
 uint32_t lri = 0, lbi=0;InterruptIn *ri; DigitalIn *dv, *dsw; Timer tsb; vA leftRotate, rightRotate, pressRotate;
                         ^~~~~~~~~~~
/home/build/prjclone/pxtapp/ky040/ky040.cpp:31:42: error: 'DigitalIn' does not name a type
 uint32_t lri = 0, lbi=0;InterruptIn *ri; DigitalIn *dv, *dsw; Timer tsb; vA leftRotate, rightRotate, pressRotate;
                                          ^~~~~~~~~
/home/build/prjclone/pxtapp/ky040/ky040.cpp:31:69: error: no matching function for call to 'codal::Timer::Timer()'
 uint32_t lri = 0, lbi=0;InterruptIn *ri; DigitalIn *dv, *dsw; Timer tsb; vA leftRotate, rightRotate, pressRotate;
```

**Comment by microbit-pauline** [comment]
@firemansamm - Are you able to look at this issue?

**Comment by raster** [comment]
Any chance this will get updated? It's the only rotary encoder extension I can find.

**Comment by firemansamm** [comment]
@microbit-pauline @microbit-sam Hi! Sorry it's been quiet - I'm no longer in charge of maintaining the packages, but I've attempted to push a branch that should work with the V2 if I understood the changes right. Would it be possible for someone to review this, as I don't have access to the V2 hardware? The branch in question is https://github.com/tinkertanker/pxt-rotary-encoder-ky040/tree/microbit-v2. cc: @yjsoon

**Comment by raster** [comment]
I tried loading the extension from the new URL but it didn't seem to work, so I cloned the new version, got it loaded, but I get "Compilation failed, please check your code for errors." Though I'm not sure where exactly to check for errors.

Note: I probably did it wrong... Doesn't look like it loaded the new version. I'll keep trying.

**Comment by firemansamm** [comment]
@raster I wasn't sure if there was a way to add a branch to a project (which is why I tagged the foundation folks first). I've cloned and merged the changes to master on https://github.com/firemansamm/pxt-rotary-encoder-ky040 - try adding that repository instead? It should give you a warning about being a non-approved extension, but that's fine. If it works good, we can go ahead with merging it into this repository.

**Comment by raster** [comment]
@firemansamm Thanks! Just gave it a try and it's not loading from the URL... I'll try tonight on another machine and give it another shot tomorrow if I still have issues.

**Comment by raster** [comment]
I got the new URL loaded, tried to save the hex, and get the message "Compilation failed, please check your code for errors."

I did open the Explorer and try again and I got what you can see in this screen capture. I don't know if this means the error is in main.ts but thought I'd mention it.

![error](https://user-images.githubusercontent.com/24936/113371511-2a276100-932c-11eb-8a87-213b864eae93.png)

**Comment by raster** [comment]
Sorry! Found one more error...
![error2](https://user-images.githubusercontent.com/24936/113372183-ab332800-932d-11eb-896e-047f42c801c8.png)

**Comment by firemansamm** [comment]
@raster I've fixed it up to a state where it should compile (at least, it does let me download the hex). Can you make sure that the version within "Project Settings" > "Edit Settings As Text" is v1.1.1 from the new URL I've given earlier?

**Comment by raster** [comment]
Okay, we've got v1.1.1 loaded. It does compile and I can load the hex onto a micro:bit V2, but the dial has no effect.

The switch seems to either do nothing, or sometimes seems to trigger on its own after the code is running for X amount of seconds. The behavior is inconsistent. (If I write separate code to account for the switch it does work, just not when using the event handler.)

_Everything does work fine on micro:bit V1.5 board_. Oh, one thing I forgot to mention... I assume left is counterclockwise and right is clockwise, if that is the case, the **on rotated Left** and **on rotated Right** event handlers are swapped, as left causes an increase and right causes a decrease. (Easy to work around, but thought I would mention it.)

Thanks again for trying to solve this! I'm happy to keep testing.

**Comment by raster** [comment]
Just a quick update: I've been able to write code using blocks in MakeCode that can work with a rotary encoder, but the code is too simplistic, and only works if the dial turns slowly. Any pointers on how to make it work in MakeCode? Should I look at the **on event** handlers in the **Control** section?

**Comment by raster** [comment]
@firemansamm Any luck with updating the extension for micro:bit V2?

**Comment by microbit-mark** [comment]
@yjsoon Could you look into this one? It looks like the extension is still not supported fully on the V2 board

**Comment by raster** [comment]
Any chance of an update for this? I've looked at the code but just cannot figure out how to fix it.

**Comment by Mireille-T** [comment]
@microbit-sam @microbit-mark I've made some updates to the extension that should now allow it to be compatible with the micro:bit v2 (released under v1.2.1), as tested locally and on the MakeCode editor linked to GitHub. I have also made the required [pull request](https://github.com/microsoft/pxt-microbit/pull/4472). May I verify if the extension works and if so, this issue has been resolved? Thank you!

**Comment by raster** [comment]
I did find another extension that seems to work: https://github.com/dsssssssss9/ky40-test-klein-

**Comment by dsssssssss9** [comment]
HI

the link in the previous comment by raster  is to my REPO, but the actual extension that i use is by a Michael klein,,, all credit must go to him!!

https://github.com/MKleinSB/pxt-KY-040

He is always very helpful if you have any questions

TTFN

**Comment by microbit-mark** [comment]
Thanks @Mireille-T ONce the PR is approved you can close this ticket

**Comment by raster** [comment]
Thanks to everyone working on solutions! We're trying to make more micro:bit content and curriculum available to teachers and students so this really helps. 👍
